# Generated by Django 3.0.2 on 2020-04-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20200403_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensora',
            old_name='client',
            new_name='cpu_freq',
        ),
        migrations.RenameField(
            model_name='sensora',
            old_name='value',
            new_name='ram_usage',
        ),
    ]
